language: node_js
node_js:
  - "node"
  - "6"

notifications:
    webhooks:
        urls:
          - https://warframestat.us/parser/travis-ci.php
        on_success: always
        on_failure: always
